### ISSUE TITLE
Is there a pytorch implementation?

### ISSUE THREAD

**Issue by CHENHUI-X** [google-research/maxvit#14]
HI Sir, I am new here, thanks for your great work. I am not very familiar with the syntax of TensorFlow. Is there a model implemented by pytorch?

**Comment by vztu** [comment]
Please check out the timm repo here: https://github.com/rwightman/pytorch-image-models

**Comment by CHENHUI-X** [comment]
> Please check out the timm repo here: https://github.com/rwightman/pytorch-image-models

Ok, thanks a lot for your reply!
