### ISSUE TITLE
maxvit-gan?

### ISSUE THREAD

**Issue by Suzan009** [google-research/maxvit#5]
how did you use max vit in gan and object detection and segmentation? Is code available? And how to fine tune this model on different data set, is it documented?

**Comment by vztu** [comment]
We recommend you to plug in our `maxvit block` into the [hit-gan](https://github.com/google-research/hit-gan) training framework by replacing the multi-axis blocks in hit-gan. Currently we don't have any plans to release detection and segmentation anytime soon. Should you be interested in using pytorch codebases, the [timm](https://github.com/rwightman/pytorch-image-models#oct-10-2022) repo has provided easy-to-use pytorch scripts to load our model as backbone to do other things. Here is an example that uses our backbone to do keypoint detection: https://github.com/tlpss/keypoint-detection/blob/main/keypoint_detection/models/backbones/maxvit_unet.py#L51
